version: '2'

networks:
  cloud:

services:
  redis1:
    image: 'redis:latest'
    container_name: redis.CSP1.cloud.com
    command: redis-server --requirepass CSP1cloud
    ports:
      - "6379:6379"
    networks:
      - cloud

  redis2:
    image: 'redis:latest'
    container_name: redis.CSP2.cloud.com
    command: redis-server --requirepass CSP2cloud
    ports:
      - "6380:6379"
    networks:
      - cloud

  redis3:
    image: 'redis:latest'
    container_name: redis.CSP3.cloud.com
    command: redis-server --requirepass CSP3cloud
    ports:
      - "6381:6379"
    networks:
      - cloud